spring:
  application:
    name: quiz-auth-service
jwt:
  secret: adjglasjdglsaglknagsnasngdanghaiuehtaeiuhgfsdkgbkashdgaiulgbaksgdbasgagaebgkabgabdsgkabgdkjabkgbadgkbaskgjabsg
  expiration: 3600000
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
