spring:
  application:
    name: quiz-auth-service
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
server:
  port: 0

  instance:
    instance-id: ${spring.application.name}:${random.value}
